spring:
  datasource:
    url: jdbc:h2:mem:proddb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    user:
      name: istiak
      password: "0000"
      roles:
        - ADMIN

server:
  port: 8080





