create table author (id bigint generated by default as identity, biography varchar(1000), date_of_birth date, first_name varchar(255), last_name varchar(255), primary key (id));
create table book (id bigint generated by default as identity, isbn varchar(255), publication_date date, summary varchar(500), title varchar(255), author_id bigint, primary key (id));

alter table book drop constraint if exists UK_ehpdfjpu1jm3hijhj4mm0hx9h;
alter table book add constraint UK_ehpdfjpu1jm3hijhj4mm0hx9h unique (isbn);
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author;


